// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogQuery struct {
	Filter               string           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Duration             *QueryDuration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Resolution           *QueryResolution `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Page                 *QueryPage       `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogQuery) Reset()         { *m = LogQuery{} }
func (m *LogQuery) String() string { return proto.CompactTextString(m) }
func (*LogQuery) ProtoMessage()    {}
func (*LogQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *LogQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogQuery.Unmarshal(m, b)
}
func (m *LogQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogQuery.Marshal(b, m, deterministic)
}
func (m *LogQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogQuery.Merge(m, src)
}
func (m *LogQuery) XXX_Size() int {
	return xxx_messageInfo_LogQuery.Size(m)
}
func (m *LogQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_LogQuery.DiscardUnknown(m)
}

var xxx_messageInfo_LogQuery proto.InternalMessageInfo

func (m *LogQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *LogQuery) GetDuration() *QueryDuration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *LogQuery) GetResolution() *QueryResolution {
	if m != nil {
		return m.Resolution
	}
	return nil
}

func (m *LogQuery) GetPage() *QueryPage {
	if m != nil {
		return m.Page
	}
	return nil
}

type QueryPage struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPage) Reset()         { *m = QueryPage{} }
func (m *QueryPage) String() string { return proto.CompactTextString(m) }
func (*QueryPage) ProtoMessage()    {}
func (*QueryPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *QueryPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPage.Unmarshal(m, b)
}
func (m *QueryPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPage.Marshal(b, m, deterministic)
}
func (m *QueryPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPage.Merge(m, src)
}
func (m *QueryPage) XXX_Size() int {
	return xxx_messageInfo_QueryPage.Size(m)
}
func (m *QueryPage) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPage.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPage proto.InternalMessageInfo

func (m *QueryPage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *QueryPage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QueryPage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryPage) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type QueryDuration struct {
	StartMs              int64    `protobuf:"varint,1,opt,name=startMs,proto3" json:"startMs,omitempty"`
	EndMs                int64    `protobuf:"varint,2,opt,name=endMs,proto3" json:"endMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDuration) Reset()         { *m = QueryDuration{} }
func (m *QueryDuration) String() string { return proto.CompactTextString(m) }
func (*QueryDuration) ProtoMessage()    {}
func (*QueryDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *QueryDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDuration.Unmarshal(m, b)
}
func (m *QueryDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDuration.Marshal(b, m, deterministic)
}
func (m *QueryDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDuration.Merge(m, src)
}
func (m *QueryDuration) XXX_Size() int {
	return xxx_messageInfo_QueryDuration.Size(m)
}
func (m *QueryDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDuration.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDuration proto.InternalMessageInfo

func (m *QueryDuration) GetStartMs() int64 {
	if m != nil {
		return m.StartMs
	}
	return 0
}

func (m *QueryDuration) GetEndMs() int64 {
	if m != nil {
		return m.EndMs
	}
	return 0
}

type QueryResolution struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResolution) Reset()         { *m = QueryResolution{} }
func (m *QueryResolution) String() string { return proto.CompactTextString(m) }
func (*QueryResolution) ProtoMessage()    {}
func (*QueryResolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *QueryResolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResolution.Unmarshal(m, b)
}
func (m *QueryResolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResolution.Marshal(b, m, deterministic)
}
func (m *QueryResolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResolution.Merge(m, src)
}
func (m *QueryResolution) XXX_Size() int {
	return xxx_messageInfo_QueryResolution.Size(m)
}
func (m *QueryResolution) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResolution.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResolution proto.InternalMessageInfo

type LogStats struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Instances            int32    `protobuf:"varint,2,opt,name=instances,proto3" json:"instances,omitempty"`
	Debug                int32    `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	Info                 int32    `protobuf:"varint,4,opt,name=info,proto3" json:"info,omitempty"`
	Warning              int32    `protobuf:"varint,5,opt,name=warning,proto3" json:"warning,omitempty"`
	Error                int32    `protobuf:"varint,6,opt,name=error,proto3" json:"error,omitempty"`
	Fatal                int32    `protobuf:"varint,7,opt,name=fatal,proto3" json:"fatal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStats) Reset()         { *m = LogStats{} }
func (m *LogStats) String() string { return proto.CompactTextString(m) }
func (*LogStats) ProtoMessage()    {}
func (*LogStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *LogStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStats.Unmarshal(m, b)
}
func (m *LogStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStats.Marshal(b, m, deterministic)
}
func (m *LogStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStats.Merge(m, src)
}
func (m *LogStats) XXX_Size() int {
	return xxx_messageInfo_LogStats.Size(m)
}
func (m *LogStats) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStats.DiscardUnknown(m)
}

var xxx_messageInfo_LogStats proto.InternalMessageInfo

func (m *LogStats) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *LogStats) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *LogStats) GetDebug() int32 {
	if m != nil {
		return m.Debug
	}
	return 0
}

func (m *LogStats) GetInfo() int32 {
	if m != nil {
		return m.Info
	}
	return 0
}

func (m *LogStats) GetWarning() int32 {
	if m != nil {
		return m.Warning
	}
	return 0
}

func (m *LogStats) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *LogStats) GetFatal() int32 {
	if m != nil {
		return m.Fatal
	}
	return 0
}

func init() {
	proto.RegisterType((*LogQuery)(nil), "common.logQuery")
	proto.RegisterType((*QueryPage)(nil), "common.queryPage")
	proto.RegisterType((*QueryDuration)(nil), "common.queryDuration")
	proto.RegisterType((*QueryResolution)(nil), "common.queryResolution")
	proto.RegisterType((*LogStats)(nil), "common.logStats")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xb6, 0x49, 0x9b, 0xe3, 0x9f, 0x6a, 0xf1, 0x27, 0x03, 0x43, 0x15, 0x09, 0xa9,
	0x53, 0x2b, 0x60, 0x60, 0x44, 0x42, 0xac, 0x95, 0xc0, 0x6c, 0x6c, 0x4e, 0xe3, 0x06, 0x4b, 0x89,
	0x1d, 0x9c, 0x8b, 0x50, 0xfb, 0xa1, 0xd8, 0xf8, 0x7e, 0xc8, 0xe7, 0xb4, 0xa5, 0x6c, 0xf7, 0xde,
	0xf9, 0xdd, 0xfd, 0x1c, 0x07, 0x8e, 0x97, 0xa6, 0xaa, 0x8c, 0x9e, 0xd5, 0xd6, 0xa0, 0x61, 0x91,
	0x57, 0xe9, 0x4f, 0x00, 0xa3, 0xd2, 0x14, 0xaf, 0xad, 0xb4, 0x6b, 0x76, 0x09, 0xd1, 0x4a, 0x95,
	0x28, 0x6d, 0x12, 0x4c, 0x82, 0x69, 0xcc, 0x3b, 0xc5, 0x6e, 0x61, 0x94, 0xb7, 0x56, 0xa0, 0x32,
	0x3a, 0xe9, 0x4d, 0x82, 0xe9, 0xd1, 0xdd, 0xc5, 0xac, 0x9b, 0xf6, 0xe9, 0x82, 0xcf, 0x5d, 0x93,
	0xef, 0x8e, 0xb1, 0x07, 0x00, 0x2b, 0x1b, 0x53, 0xb6, 0x14, 0xea, 0x53, 0xe8, 0xea, 0x20, 0xc4,
	0x77, 0x6d, 0xfe, 0xe7, 0x28, 0xbb, 0x81, 0x41, 0x2d, 0x0a, 0x99, 0x0c, 0x28, 0x32, 0x3e, 0x88,
	0xbc, 0x88, 0x42, 0x72, 0x6a, 0xa7, 0x02, 0xe2, 0x9d, 0xc5, 0x18, 0x0c, 0x70, 0x5d, 0xcb, 0x8e,
	0x9a, 0x6a, 0x76, 0x0d, 0x31, 0xaa, 0x4a, 0x36, 0x28, 0xaa, 0x9a, 0xa0, 0xfb, 0x7c, 0x6f, 0xb0,
	0x53, 0xe8, 0xa9, 0x9c, 0xb0, 0x62, 0xde, 0x53, 0xb9, 0x9b, 0xd0, 0xa8, 0x8d, 0xdf, 0x1a, 0x72,
	0xaa, 0xd3, 0x47, 0x38, 0x39, 0xb8, 0x1d, 0x4b, 0x60, 0xd8, 0xa0, 0xb0, 0xb8, 0x68, 0x68, 0x53,
	0x9f, 0x6f, 0x25, 0x3b, 0x87, 0x50, 0xea, 0x7c, 0xd1, 0x74, 0x8b, 0xbc, 0x48, 0xc7, 0x70, 0xf6,
	0xef, 0xa6, 0xe9, 0xb7, 0xff, 0xdc, 0x6f, 0x28, 0x90, 0x52, 0x68, 0x50, 0x94, 0x34, 0x2d, 0xe4,
	0x5e, 0x38, 0x70, 0xa5, 0x1b, 0x14, 0x7a, 0x29, 0xfd, 0xbc, 0x90, 0xef, 0x0d, 0x97, 0xc9, 0x65,
	0xd6, 0x16, 0xc4, 0x1e, 0x72, 0x2f, 0x1c, 0xbe, 0xd2, 0x2b, 0xb3, 0xc5, 0x77, 0xb5, 0xa3, 0xfd,
	0x12, 0x56, 0x2b, 0x5d, 0x24, 0x21, 0xd9, 0x5b, 0x49, 0xb4, 0xd6, 0x1a, 0x9b, 0x44, 0x7e, 0x06,
	0x09, 0xe7, 0xae, 0x84, 0xa3, 0x19, 0x7a, 0x97, 0xc4, 0x53, 0xfa, 0x3e, 0x29, 0x14, 0x7e, 0xb4,
	0x99, 0x7b, 0x88, 0x79, 0x56, 0x2a, 0xdc, 0x94, 0xa6, 0x98, 0xd3, 0x4f, 0x34, 0xf7, 0x6f, 0x93,
	0x45, 0xa4, 0xee, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x02, 0x86, 0xb9, 0xa7, 0x62, 0x02, 0x00,
	0x00,
}
