// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge.proto

package edge

import (
	fmt "fmt"
	log "github.com/blitzlog/proto/log"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostLogsRequest struct {
	TokenId              string    `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Logs                 *log.Logs `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	Metrics              *Metrics  `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PostLogsRequest) Reset()         { *m = PostLogsRequest{} }
func (m *PostLogsRequest) String() string { return proto.CompactTextString(m) }
func (*PostLogsRequest) ProtoMessage()    {}
func (*PostLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{0}
}

func (m *PostLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLogsRequest.Unmarshal(m, b)
}
func (m *PostLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLogsRequest.Marshal(b, m, deterministic)
}
func (m *PostLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLogsRequest.Merge(m, src)
}
func (m *PostLogsRequest) XXX_Size() int {
	return xxx_messageInfo_PostLogsRequest.Size(m)
}
func (m *PostLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostLogsRequest proto.InternalMessageInfo

func (m *PostLogsRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *PostLogsRequest) GetLogs() *log.Logs {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *PostLogsRequest) GetMetrics() *Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metrics struct {
	Latency              int32    `protobuf:"varint,1,opt,name=latency,proto3" json:"latency,omitempty"`
	ErrCount             int32    `protobuf:"varint,2,opt,name=errCount,proto3" json:"errCount,omitempty"`
	LogChannelSize       int32    `protobuf:"varint,3,opt,name=logChannelSize,proto3" json:"logChannelSize,omitempty"`
	EdgeChannelSize      int32    `protobuf:"varint,4,opt,name=edgeChannelSize,proto3" json:"edgeChannelSize,omitempty"`
	LocalChannelSize     int32    `protobuf:"varint,5,opt,name=localChannelSize,proto3" json:"localChannelSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{1}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetLatency() int32 {
	if m != nil {
		return m.Latency
	}
	return 0
}

func (m *Metrics) GetErrCount() int32 {
	if m != nil {
		return m.ErrCount
	}
	return 0
}

func (m *Metrics) GetLogChannelSize() int32 {
	if m != nil {
		return m.LogChannelSize
	}
	return 0
}

func (m *Metrics) GetEdgeChannelSize() int32 {
	if m != nil {
		return m.EdgeChannelSize
	}
	return 0
}

func (m *Metrics) GetLocalChannelSize() int32 {
	if m != nil {
		return m.LocalChannelSize
	}
	return 0
}

type PostLogsResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	LogLevel             log.Level `protobuf:"varint,2,opt,name=logLevel,proto3,enum=log.Level" json:"logLevel,omitempty"`
	LogVerbosity         int32     `protobuf:"varint,3,opt,name=logVerbosity,proto3" json:"logVerbosity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PostLogsResponse) Reset()         { *m = PostLogsResponse{} }
func (m *PostLogsResponse) String() string { return proto.CompactTextString(m) }
func (*PostLogsResponse) ProtoMessage()    {}
func (*PostLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{2}
}

func (m *PostLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLogsResponse.Unmarshal(m, b)
}
func (m *PostLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLogsResponse.Marshal(b, m, deterministic)
}
func (m *PostLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLogsResponse.Merge(m, src)
}
func (m *PostLogsResponse) XXX_Size() int {
	return xxx_messageInfo_PostLogsResponse.Size(m)
}
func (m *PostLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostLogsResponse proto.InternalMessageInfo

func (m *PostLogsResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PostLogsResponse) GetLogLevel() log.Level {
	if m != nil {
		return m.LogLevel
	}
	return log.Level_none
}

func (m *PostLogsResponse) GetLogVerbosity() int32 {
	if m != nil {
		return m.LogVerbosity
	}
	return 0
}

type AuthRequest struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyId                string   `protobuf:"bytes,2,opt,name=keyId,proto3" json:"keyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{3}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AuthRequest) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

type AuthResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	TokenId              string   `protobuf:"bytes,2,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{4}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthResponse) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func init() {
	proto.RegisterType((*PostLogsRequest)(nil), "edge.postLogsRequest")
	proto.RegisterType((*Metrics)(nil), "edge.metrics")
	proto.RegisterType((*PostLogsResponse)(nil), "edge.postLogsResponse")
	proto.RegisterType((*AuthRequest)(nil), "edge.authRequest")
	proto.RegisterType((*AuthResponse)(nil), "edge.authResponse")
}

func init() { proto.RegisterFile("edge.proto", fileDescriptor_cab1176173a95651) }

var fileDescriptor_cab1176173a95651 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x86, 0x49, 0xd9, 0xd0, 0xdd, 0x69, 0x69, 0xcb, 0x08, 0x50, 0x14, 0x09, 0xb4, 0xca, 0xa1,
	0x44, 0x1c, 0xb2, 0x68, 0x39, 0x70, 0x01, 0x21, 0xd1, 0x53, 0xa5, 0x9e, 0x8c, 0xc4, 0x81, 0x5b,
	0x3e, 0x46, 0xde, 0xa8, 0xae, 0x67, 0x89, 0x9d, 0x4a, 0xdb, 0x13, 0x7f, 0x8c, 0xff, 0x86, 0x62,
	0x27, 0x4b, 0x36, 0x48, 0xbd, 0x79, 0x1e, 0xbf, 0xf6, 0x3b, 0x5f, 0x00, 0x54, 0x49, 0xca, 0xb6,
	0x0d, 0x5b, 0xc6, 0x59, 0x77, 0x8e, 0x17, 0x8a, 0xa5, 0x07, 0x89, 0x81, 0xf3, 0x2d, 0x1b, 0x7b,
	0xc3, 0xd2, 0x08, 0xfa, 0xd5, 0x92, 0xb1, 0x18, 0xc1, 0xb1, 0xe5, 0x5b, 0xd2, 0xd7, 0x55, 0x14,
	0x2c, 0x83, 0x74, 0x21, 0x86, 0x10, 0xdf, 0xc0, 0x4c, 0xb1, 0x34, 0xd1, 0xd1, 0x32, 0x48, 0x4f,
	0xd6, 0x8b, 0xac, 0xfb, 0xa6, 0x03, 0xc2, 0x61, 0x7c, 0x07, 0xc7, 0x77, 0x64, 0x9b, 0xba, 0x34,
	0xd1, 0x53, 0xa7, 0x78, 0x9e, 0x39, 0xeb, 0x1e, 0x8a, 0xe1, 0x36, 0xf9, 0x13, 0xec, 0x95, 0x9d,
	0x9b, 0xca, 0x2d, 0xe9, 0x72, 0xe7, 0xdc, 0x42, 0x31, 0x84, 0x18, 0xc3, 0x9c, 0x9a, 0xe6, 0x8a,
	0x5b, 0x6d, 0x9d, 0x63, 0x28, 0xf6, 0x31, 0x5e, 0xc2, 0x99, 0x62, 0x79, 0xb5, 0xc9, 0xb5, 0x26,
	0xf5, 0xbd, 0x7e, 0x20, 0xe7, 0x18, 0x8a, 0x09, 0xc5, 0x14, 0xce, 0xbb, 0x14, 0xc6, 0xc2, 0x99,
	0x13, 0x4e, 0x31, 0xbe, 0x87, 0x0b, 0xc5, 0x65, 0xae, 0xc6, 0xd2, 0xd0, 0x49, 0xff, 0xe3, 0x49,
	0x03, 0x17, 0xff, 0x9a, 0x66, 0xb6, 0xac, 0x0d, 0x21, 0xc2, 0xac, 0xe4, 0x8a, 0xfa, 0x22, 0xdc,
	0x19, 0x2f, 0x61, 0xae, 0x58, 0xde, 0xd0, 0x3d, 0x29, 0x57, 0xc1, 0xd9, 0x1a, 0x7c, 0xcf, 0x3a,
	0x22, 0xf6, 0x77, 0x98, 0xc0, 0xa9, 0x62, 0xf9, 0x83, 0x9a, 0x82, 0x4d, 0x6d, 0x77, 0x7d, 0x2d,
	0x07, 0x2c, 0xf9, 0x02, 0x27, 0x79, 0x6b, 0x37, 0xa3, 0x21, 0xdd, 0x53, 0x63, 0x6a, 0xd6, 0xc3,
	0x90, 0xfa, 0x10, 0x5f, 0x42, 0x78, 0x4b, 0xbb, 0xeb, 0xca, 0x39, 0x2e, 0x84, 0x0f, 0x92, 0xcf,
	0x70, 0xea, 0x9f, 0x3f, 0x92, 0xee, 0x68, 0xf0, 0x47, 0x07, 0x83, 0x5f, 0xff, 0x0e, 0xc0, 0x6d,
	0x0e, 0x7e, 0xf2, 0xdf, 0x90, 0xb6, 0x75, 0x99, 0x5b, 0xc2, 0x17, 0x7e, 0xc2, 0xa3, 0xcc, 0x62,
	0x1c, 0x23, 0xef, 0x96, 0x3c, 0xc1, 0xaf, 0x30, 0x1f, 0x5a, 0x86, 0xaf, 0xbc, 0x62, 0xb2, 0x77,
	0xf1, 0xeb, 0x29, 0x1e, 0x1e, 0xa7, 0xc1, 0x87, 0xe0, 0xdb, 0xf2, 0xe7, 0x5b, 0x59, 0xdb, 0x4d,
	0x5b, 0x64, 0x25, 0xdf, 0xad, 0x0a, 0x55, 0xdb, 0x07, 0xc5, 0x72, 0xe5, 0xb6, 0x78, 0xd5, 0x3d,
	0x2c, 0x9e, 0xb9, 0xf3, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0xcc, 0x12, 0x09, 0xf0,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EdgeClient is the client API for Edge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeClient interface {
	// authenticate client
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// post logs from client to edge server.
	PostLogs(ctx context.Context, opts ...grpc.CallOption) (Edge_PostLogsClient, error)
}

type edgeClient struct {
	cc *grpc.ClientConn
}

func NewEdgeClient(cc *grpc.ClientConn) EdgeClient {
	return &edgeClient{cc}
}

func (c *edgeClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/edge.edge/authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClient) PostLogs(ctx context.Context, opts ...grpc.CallOption) (Edge_PostLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Edge_serviceDesc.Streams[0], "/edge.edge/postLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &edgePostLogsClient{stream}
	return x, nil
}

type Edge_PostLogsClient interface {
	Send(*PostLogsRequest) error
	Recv() (*PostLogsResponse, error)
	grpc.ClientStream
}

type edgePostLogsClient struct {
	grpc.ClientStream
}

func (x *edgePostLogsClient) Send(m *PostLogsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *edgePostLogsClient) Recv() (*PostLogsResponse, error) {
	m := new(PostLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EdgeServer is the server API for Edge service.
type EdgeServer interface {
	// authenticate client
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// post logs from client to edge server.
	PostLogs(Edge_PostLogsServer) error
}

func RegisterEdgeServer(s *grpc.Server, srv EdgeServer) {
	s.RegisterService(&_Edge_serviceDesc, srv)
}

func _Edge_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.edge/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edge_PostLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EdgeServer).PostLogs(&edgePostLogsServer{stream})
}

type Edge_PostLogsServer interface {
	Send(*PostLogsResponse) error
	Recv() (*PostLogsRequest, error)
	grpc.ServerStream
}

type edgePostLogsServer struct {
	grpc.ServerStream
}

func (x *edgePostLogsServer) Send(m *PostLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *edgePostLogsServer) Recv() (*PostLogsRequest, error) {
	m := new(PostLogsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Edge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edge.edge",
	HandlerType: (*EdgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "authenticate",
			Handler:    _Edge_Authenticate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "postLogs",
			Handler:       _Edge_PostLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "edge.proto",
}
