// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	common "github.com/blitzlog/proto/common"
	log "github.com/blitzlog/proto/log"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateTokenRequest struct {
	ExternalToken        string   `protobuf:"bytes,1,opt,name=externalToken,proto3" json:"externalToken,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenRequest) Reset()         { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()    {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenRequest.Unmarshal(m, b)
}
func (m *CreateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenRequest.Merge(m, src)
}
func (m *CreateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTokenRequest.Size(m)
}
func (m *CreateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenRequest proto.InternalMessageInfo

func (m *CreateTokenRequest) GetExternalToken() string {
	if m != nil {
		return m.ExternalToken
	}
	return ""
}

func (m *CreateTokenRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type CreateTokenResponse struct {
	Token                string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User      `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Accounts             []*Account `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateTokenResponse) Reset()         { *m = CreateTokenResponse{} }
func (m *CreateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTokenResponse) ProtoMessage()    {}
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenResponse.Unmarshal(m, b)
}
func (m *CreateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenResponse.Merge(m, src)
}
func (m *CreateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTokenResponse.Size(m)
}
func (m *CreateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenResponse proto.InternalMessageInfo

func (m *CreateTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateTokenResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateTokenResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type CreateAccountRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateOrgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrgRequest) Reset()         { *m = CreateOrgRequest{} }
func (m *CreateOrgRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrgRequest) ProtoMessage()    {}
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *CreateOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrgRequest.Unmarshal(m, b)
}
func (m *CreateOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrgRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrgRequest.Merge(m, src)
}
func (m *CreateOrgRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrgRequest.Size(m)
}
func (m *CreateOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrgRequest proto.InternalMessageInfo

type CreateOrgResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrgResponse) Reset()         { *m = CreateOrgResponse{} }
func (m *CreateOrgResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrgResponse) ProtoMessage()    {}
func (*CreateOrgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *CreateOrgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrgResponse.Unmarshal(m, b)
}
func (m *CreateOrgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrgResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrgResponse.Merge(m, src)
}
func (m *CreateOrgResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrgResponse.Size(m)
}
func (m *CreateOrgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrgResponse proto.InternalMessageInfo

type AddUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserRequest) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AddUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

type CreateKeyRequest struct {
	Tags                 map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateKeyRequest) Reset()         { *m = CreateKeyRequest{} }
func (m *CreateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateKeyRequest) ProtoMessage()    {}
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *CreateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyRequest.Unmarshal(m, b)
}
func (m *CreateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyRequest.Marshal(b, m, deterministic)
}
func (m *CreateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyRequest.Merge(m, src)
}
func (m *CreateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateKeyRequest.Size(m)
}
func (m *CreateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyRequest proto.InternalMessageInfo

func (m *CreateKeyRequest) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateKeyResponse struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateKeyResponse) Reset()         { *m = CreateKeyResponse{} }
func (m *CreateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateKeyResponse) ProtoMessage()    {}
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *CreateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyResponse.Unmarshal(m, b)
}
func (m *CreateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyResponse.Marshal(b, m, deterministic)
}
func (m *CreateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyResponse.Merge(m, src)
}
func (m *CreateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateKeyResponse.Size(m)
}
func (m *CreateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyResponse proto.InternalMessageInfo

func (m *CreateKeyResponse) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type UpdateKeyRequest struct {
	Tags                 map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateKeyRequest) Reset()         { *m = UpdateKeyRequest{} }
func (m *UpdateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateKeyRequest) ProtoMessage()    {}
func (*UpdateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *UpdateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateKeyRequest.Unmarshal(m, b)
}
func (m *UpdateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateKeyRequest.Merge(m, src)
}
func (m *UpdateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateKeyRequest.Size(m)
}
func (m *UpdateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateKeyRequest proto.InternalMessageInfo

func (m *UpdateKeyRequest) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UpdateKeyResponse struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateKeyResponse) Reset()         { *m = UpdateKeyResponse{} }
func (m *UpdateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateKeyResponse) ProtoMessage()    {}
func (*UpdateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *UpdateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateKeyResponse.Unmarshal(m, b)
}
func (m *UpdateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateKeyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateKeyResponse.Merge(m, src)
}
func (m *UpdateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateKeyResponse.Size(m)
}
func (m *UpdateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateKeyResponse proto.InternalMessageInfo

func (m *UpdateKeyResponse) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetKeysResponse struct {
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysResponse) Reset()         { *m = GetKeysResponse{} }
func (m *GetKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeysResponse) ProtoMessage()    {}
func (*GetKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *GetKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysResponse.Unmarshal(m, b)
}
func (m *GetKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysResponse.Marshal(b, m, deterministic)
}
func (m *GetKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysResponse.Merge(m, src)
}
func (m *GetKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeysResponse.Size(m)
}
func (m *GetKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysResponse proto.InternalMessageInfo

func (m *GetKeysResponse) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetLogsRequest struct {
	Query                *common.LogQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetLogsRequest) Reset()         { *m = GetLogsRequest{} }
func (m *GetLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogsRequest) ProtoMessage()    {}
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *GetLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsRequest.Unmarshal(m, b)
}
func (m *GetLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsRequest.Merge(m, src)
}
func (m *GetLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogsRequest.Size(m)
}
func (m *GetLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsRequest proto.InternalMessageInfo

func (m *GetLogsRequest) GetQuery() *common.LogQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetLogsResponse struct {
	Logs                 []*log.Log `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetLogsResponse) Reset()         { *m = GetLogsResponse{} }
func (m *GetLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLogsResponse) ProtoMessage()    {}
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *GetLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsResponse.Unmarshal(m, b)
}
func (m *GetLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsResponse.Merge(m, src)
}
func (m *GetLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLogsResponse.Size(m)
}
func (m *GetLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsResponse proto.InternalMessageInfo

func (m *GetLogsResponse) GetLogs() []*log.Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type GetLogStatsRequest struct {
	Query                *common.LogQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetLogStatsRequest) Reset()         { *m = GetLogStatsRequest{} }
func (m *GetLogStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogStatsRequest) ProtoMessage()    {}
func (*GetLogStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *GetLogStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogStatsRequest.Unmarshal(m, b)
}
func (m *GetLogStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetLogStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogStatsRequest.Merge(m, src)
}
func (m *GetLogStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogStatsRequest.Size(m)
}
func (m *GetLogStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogStatsRequest proto.InternalMessageInfo

func (m *GetLogStatsRequest) GetQuery() *common.LogQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetLogStatsResponse struct {
	Stats                *common.LogStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetLogStatsResponse) Reset()         { *m = GetLogStatsResponse{} }
func (m *GetLogStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLogStatsResponse) ProtoMessage()    {}
func (*GetLogStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *GetLogStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogStatsResponse.Unmarshal(m, b)
}
func (m *GetLogStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetLogStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogStatsResponse.Merge(m, src)
}
func (m *GetLogStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLogStatsResponse.Size(m)
}
func (m *GetLogStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogStatsResponse proto.InternalMessageInfo

func (m *GetLogStatsResponse) GetStats() *common.LogStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type GetLogMetricsRequest struct {
	Query                *common.LogQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetLogMetricsRequest) Reset()         { *m = GetLogMetricsRequest{} }
func (m *GetLogMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogMetricsRequest) ProtoMessage()    {}
func (*GetLogMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *GetLogMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogMetricsRequest.Unmarshal(m, b)
}
func (m *GetLogMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogMetricsRequest.Marshal(b, m, deterministic)
}
func (m *GetLogMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogMetricsRequest.Merge(m, src)
}
func (m *GetLogMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogMetricsRequest.Size(m)
}
func (m *GetLogMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogMetricsRequest proto.InternalMessageInfo

func (m *GetLogMetricsRequest) GetQuery() *common.LogQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetLogMetricsResponse struct {
	Timeseries           *common.Timeseries `protobuf:"bytes,1,opt,name=timeseries,proto3" json:"timeseries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetLogMetricsResponse) Reset()         { *m = GetLogMetricsResponse{} }
func (m *GetLogMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLogMetricsResponse) ProtoMessage()    {}
func (*GetLogMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *GetLogMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogMetricsResponse.Unmarshal(m, b)
}
func (m *GetLogMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogMetricsResponse.Marshal(b, m, deterministic)
}
func (m *GetLogMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogMetricsResponse.Merge(m, src)
}
func (m *GetLogMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLogMetricsResponse.Size(m)
}
func (m *GetLogMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogMetricsResponse proto.InternalMessageInfo

func (m *GetLogMetricsResponse) GetTimeseries() *common.Timeseries {
	if m != nil {
		return m.Timeseries
	}
	return nil
}

type GetUsageResponse struct {
	Usages               []*Usage `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsageResponse) Reset()         { *m = GetUsageResponse{} }
func (m *GetUsageResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsageResponse) ProtoMessage()    {}
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *GetUsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsageResponse.Unmarshal(m, b)
}
func (m *GetUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsageResponse.Marshal(b, m, deterministic)
}
func (m *GetUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsageResponse.Merge(m, src)
}
func (m *GetUsageResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsageResponse.Size(m)
}
func (m *GetUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsageResponse proto.InternalMessageInfo

func (m *GetUsageResponse) GetUsages() []*Usage {
	if m != nil {
		return m.Usages
	}
	return nil
}

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateInstancesRequest struct {
	Instances            []string `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	LogLevel             string   `protobuf:"bytes,2,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	LogVerbosity         int32    `protobuf:"varint,3,opt,name=logVerbosity,proto3" json:"logVerbosity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstancesRequest) Reset()         { *m = UpdateInstancesRequest{} }
func (m *UpdateInstancesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInstancesRequest) ProtoMessage()    {}
func (*UpdateInstancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *UpdateInstancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstancesRequest.Unmarshal(m, b)
}
func (m *UpdateInstancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstancesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInstancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstancesRequest.Merge(m, src)
}
func (m *UpdateInstancesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInstancesRequest.Size(m)
}
func (m *UpdateInstancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstancesRequest proto.InternalMessageInfo

func (m *UpdateInstancesRequest) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *UpdateInstancesRequest) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *UpdateInstancesRequest) GetLogVerbosity() int32 {
	if m != nil {
		return m.LogVerbosity
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Usage struct {
	StartMs              int64    `protobuf:"varint,1,opt,name=startMs,proto3" json:"startMs,omitempty"`
	EndMs                int64    `protobuf:"varint,2,opt,name=endMs,proto3" json:"endMs,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Usage                int64    `protobuf:"varint,4,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetStartMs() int64 {
	if m != nil {
		return m.StartMs
	}
	return 0
}

func (m *Usage) GetEndMs() int64 {
	if m != nil {
		return m.EndMs
	}
	return 0
}

func (m *Usage) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Usage) GetUsage() int64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

type Key struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Key) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Key) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateTokenRequest)(nil), "api.createTokenRequest")
	proto.RegisterType((*CreateTokenResponse)(nil), "api.createTokenResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "api.createAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "api.createAccountResponse")
	proto.RegisterType((*GetAccountsResponse)(nil), "api.getAccountsResponse")
	proto.RegisterType((*GetAccountResponse)(nil), "api.getAccountResponse")
	proto.RegisterType((*CreateOrgRequest)(nil), "api.createOrgRequest")
	proto.RegisterType((*CreateOrgResponse)(nil), "api.createOrgResponse")
	proto.RegisterType((*AddUserRequest)(nil), "api.addUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "api.addUserResponse")
	proto.RegisterType((*CreateKeyRequest)(nil), "api.createKeyRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.createKeyRequest.TagsEntry")
	proto.RegisterType((*CreateKeyResponse)(nil), "api.createKeyResponse")
	proto.RegisterType((*UpdateKeyRequest)(nil), "api.updateKeyRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.updateKeyRequest.TagsEntry")
	proto.RegisterType((*UpdateKeyResponse)(nil), "api.updateKeyResponse")
	proto.RegisterType((*GetKeysResponse)(nil), "api.getKeysResponse")
	proto.RegisterType((*GetLogsRequest)(nil), "api.getLogsRequest")
	proto.RegisterType((*GetLogsResponse)(nil), "api.getLogsResponse")
	proto.RegisterType((*GetLogStatsRequest)(nil), "api.getLogStatsRequest")
	proto.RegisterType((*GetLogStatsResponse)(nil), "api.getLogStatsResponse")
	proto.RegisterType((*GetLogMetricsRequest)(nil), "api.getLogMetricsRequest")
	proto.RegisterType((*GetLogMetricsResponse)(nil), "api.getLogMetricsResponse")
	proto.RegisterType((*GetUsageResponse)(nil), "api.getUsageResponse")
	proto.RegisterType((*GetUsersResponse)(nil), "api.getUsersResponse")
	proto.RegisterType((*UpdateInstancesRequest)(nil), "api.updateInstancesRequest")
	proto.RegisterType((*User)(nil), "api.user")
	proto.RegisterType((*Account)(nil), "api.account")
	proto.RegisterType((*Usage)(nil), "api.usage")
	proto.RegisterType((*Key)(nil), "api.key")
	proto.RegisterMapType((map[string]string)(nil), "api.key.TagsEntry")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x6b, 0x1b, 0x47,
	0x10, 0xe6, 0x74, 0x52, 0xe2, 0x1b, 0xbb, 0x8e, 0xb2, 0x76, 0x8a, 0x10, 0x0e, 0x16, 0x4b, 0x31,
	0x7a, 0xb2, 0x40, 0x86, 0x36, 0x94, 0xb4, 0xa1, 0x85, 0x3e, 0x04, 0xdb, 0x94, 0x5e, 0x93, 0x14,
	0xfa, 0x50, 0x58, 0xe9, 0x86, 0xed, 0xa2, 0xd3, 0xed, 0xe5, 0x76, 0x4f, 0xf4, 0xfa, 0xd4, 0x3f,
	0xa2, 0x7f, 0x70, 0xd9, 0x5f, 0x77, 0x67, 0xc5, 0xb4, 0x35, 0xf8, 0x6d, 0xe7, 0xdb, 0x99, 0xf9,
	0xbe, 0xd9, 0xdb, 0xfd, 0x24, 0x48, 0x58, 0x29, 0x2e, 0xcb, 0x4a, 0x6a, 0x49, 0x62, 0x56, 0x8a,
	0x69, 0x92, 0x4b, 0xee, 0xe2, 0xe9, 0xd1, 0x5a, 0x6e, 0xb7, 0xb2, 0xf0, 0xd1, 0x58, 0x8b, 0x2d,
	0x2a, 0xac, 0x04, 0x2a, 0x87, 0xd0, 0x0f, 0x40, 0xd6, 0x15, 0x32, 0x8d, 0xef, 0xe4, 0x06, 0x8b,
	0x14, 0x3f, 0xd6, 0xa8, 0x34, 0xf9, 0x02, 0x3e, 0xc3, 0x3f, 0x34, 0x56, 0x05, 0xcb, 0x2d, 0x3e,
	0x89, 0x66, 0xd1, 0x3c, 0x49, 0xef, 0x82, 0x64, 0x0a, 0x07, 0x65, 0x25, 0x77, 0x22, 0xc3, 0x6a,
	0x32, 0xb0, 0x09, 0x6d, 0x4c, 0x35, 0x9c, 0xdc, 0xe9, 0xab, 0x4a, 0x59, 0x28, 0x24, 0xa7, 0x30,
	0xd2, 0xbd, 0x86, 0x2e, 0x20, 0x2f, 0x61, 0x58, 0x2b, 0xdf, 0xe4, 0x70, 0x99, 0x5c, 0x9a, 0x71,
	0x0c, 0x90, 0x5a, 0x98, 0xcc, 0xe1, 0x80, 0xad, 0xd7, 0xb2, 0x2e, 0xb4, 0x9a, 0xc4, 0xb3, 0x78,
	0x7e, 0xb8, 0x3c, 0xb2, 0x29, 0x1e, 0x4c, 0xdb, 0x5d, 0xfa, 0x2d, 0x9c, 0x3a, 0xd6, 0xef, 0xfc,
	0x96, 0x9f, 0x87, 0xc0, 0x50, 0x37, 0x25, 0x7a, 0x56, 0xbb, 0x36, 0x58, 0xc1, 0xb6, 0xe8, 0x95,
	0xdb, 0x35, 0x7d, 0x03, 0x2f, 0xf6, 0xea, 0xbd, 0xee, 0x0b, 0x78, 0xea, 0x49, 0x6c, 0x8f, 0x7d,
	0x05, 0x61, 0x93, 0xbe, 0x81, 0x13, 0x8e, 0xda, 0x57, 0xab, 0xb6, 0xbc, 0x3f, 0x41, 0xf4, 0xaf,
	0x13, 0xbc, 0x06, 0xd2, 0x35, 0x78, 0x30, 0x3d, 0x81, 0xb1, 0xd3, 0xff, 0x63, 0xc5, 0xfd, 0xec,
	0xf4, 0x04, 0x9e, 0xf7, 0x30, 0xd7, 0x90, 0xbe, 0x86, 0x63, 0x96, 0x65, 0xef, 0xcd, 0x19, 0xfb,
	0x23, 0x3a, 0x85, 0x11, 0x6e, 0x99, 0xc8, 0xc3, 0x97, 0xb1, 0x81, 0x41, 0x2b, 0x99, 0xa3, 0x9a,
	0x0c, 0x66, 0xb1, 0x41, 0x6d, 0x40, 0x9f, 0xc3, 0xb3, 0xb6, 0xda, 0x37, 0xfc, 0x2b, 0x0a, 0xd4,
	0xd7, 0xd8, 0x84, 0x9e, 0x57, 0x30, 0xd4, 0x8c, 0x87, 0x91, 0xcf, 0xad, 0xe6, 0xfd, 0xa4, 0xcb,
	0x77, 0x8c, 0xab, 0x1f, 0x0a, 0x5d, 0x35, 0xa9, 0x4d, 0x9e, 0x7e, 0x05, 0x49, 0x0b, 0x91, 0x31,
	0xc4, 0x1b, 0x6c, 0xbc, 0x26, 0xb3, 0x34, 0x8a, 0x76, 0x2c, 0xaf, 0xc3, 0x77, 0x73, 0xc1, 0xd7,
	0x83, 0x57, 0x11, 0x5d, 0x84, 0x41, 0x6d, 0x73, 0x7f, 0x72, 0xd3, 0xae, 0xc1, 0xe1, 0xf2, 0xc0,
	0x2a, 0xd8, 0x60, 0x63, 0x5b, 0x59, 0xcd, 0x75, 0x99, 0xfd, 0xb7, 0xe6, 0xfd, 0xa4, 0x47, 0xd5,
	0xdc, 0x6b, 0xfe, 0x3f, 0x34, 0x2f, 0xe0, 0x19, 0x47, 0x7d, 0x8d, 0x4d, 0x77, 0xb9, 0xce, 0x60,
	0xb8, 0xc1, 0x26, 0x28, 0xee, 0xf2, 0x2d, 0x4a, 0x5f, 0xc1, 0x31, 0x47, 0x7d, 0x23, 0xb9, 0x0a,
	0x13, 0x5e, 0xc0, 0xe8, 0x63, 0x8d, 0x55, 0x20, 0x18, 0x5f, 0x7a, 0x8b, 0xc8, 0x25, 0xff, 0xc9,
	0xe0, 0xa9, 0xdb, 0xf6, 0x54, 0xae, 0xb2, 0xa3, 0xca, 0x25, 0xef, 0xa8, 0x8c, 0xcf, 0xe4, 0x92,
	0xa7, 0x16, 0xf5, 0x77, 0xf7, 0x46, 0xf2, 0x9f, 0x35, 0xd3, 0x0f, 0xa6, 0xfb, 0xc6, 0x3e, 0x9d,
	0xae, 0xba, 0xbd, 0xfa, 0x23, 0x65, 0x80, 0x7b, 0xca, 0x5d, 0xa2, 0xdb, 0x36, 0x4f, 0xdf, 0x95,
	0xdf, 0xa2, 0xae, 0xc4, 0xfa, 0xc1, 0xf4, 0xd7, 0xf0, 0x62, 0xaf, 0xde, 0x0b, 0x58, 0x02, 0x74,
	0xae, 0xe9, 0xbb, 0x90, 0xd0, 0xa5, 0xdb, 0x49, 0x7b, 0x59, 0xf4, 0x4b, 0x18, 0x73, 0xd4, 0xef,
	0x15, 0xe3, 0xd8, 0xf6, 0xa1, 0xf0, 0xa4, 0x36, 0x40, 0x38, 0x3d, 0xf0, 0x36, 0x67, 0x72, 0xfc,
	0x0e, 0xbd, 0xf2, 0x75, 0x58, 0x75, 0xfc, 0xe7, 0x30, 0x32, 0x2e, 0x18, 0xca, 0x7a, 0xee, 0xe8,
	0x70, 0xba, 0x83, 0xcf, 0xdd, 0x1d, 0x7a, 0x5b, 0x28, 0xcd, 0x8a, 0x35, 0xb6, 0xb3, 0x9f, 0x41,
	0x22, 0x02, 0x66, 0xcb, 0x93, 0xb4, 0x03, 0x8c, 0x7d, 0xe7, 0x92, 0xdf, 0xe0, 0x0e, 0xf3, 0x60,
	0xdf, 0x21, 0x26, 0x14, 0x8e, 0x72, 0xc9, 0x3f, 0x60, 0xb5, 0x92, 0x4a, 0xe8, 0x66, 0x12, 0xcf,
	0xa2, 0xf9, 0x28, 0xbd, 0x83, 0xd1, 0xdf, 0x9c, 0x6b, 0x93, 0x63, 0x18, 0x88, 0xcc, 0x5f, 0xf7,
	0x81, 0xc8, 0x3a, 0x27, 0x19, 0xdc, 0xeb, 0x24, 0x71, 0xcf, 0x49, 0x8c, 0x86, 0x4c, 0x28, 0xb6,
	0xca, 0x31, 0x9b, 0x0c, 0x67, 0xd1, 0xfc, 0x20, 0x6d, 0x63, 0xfa, 0x4b, 0x6b, 0x7a, 0x9f, 0x50,
	0x04, 0x3f, 0x1f, 0xdc, 0xe3, 0xe7, 0x71, 0xe7, 0xe7, 0x1d, 0xe9, 0xb0, 0x6f, 0x5f, 0x6b, 0x73,
	0xa2, 0x8c, 0x23, 0x99, 0xc0, 0x53, 0xa5, 0x59, 0xa5, 0x6f, 0xdd, 0x77, 0x8d, 0xd3, 0x10, 0xda,
	0x19, 0x8a, 0xec, 0x56, 0x59, 0x86, 0x38, 0x75, 0x81, 0x41, 0x73, 0xb1, 0x15, 0xda, 0x72, 0xc4,
	0xa9, 0x0b, 0x0c, 0x6a, 0xdb, 0xd9, 0x01, 0xe2, 0xd4, 0x05, 0xf4, 0xef, 0xc8, 0xbe, 0xe2, 0x4f,
	0xa4, 0x9f, 0x41, 0xe2, 0xa7, 0x7a, 0x9b, 0x79, 0xfd, 0x1d, 0x40, 0x2e, 0xbc, 0xfb, 0xb8, 0x9f,
	0x39, 0x12, 0xde, 0xf2, 0xa3, 0x19, 0xce, 0xf7, 0xe7, 0xbf, 0xbe, 0xe4, 0x42, 0xff, 0x5e, 0xaf,
	0xcc, 0x0d, 0x5e, 0xac, 0x72, 0xa1, 0xff, 0xcc, 0x25, 0x5f, 0xd8, 0x3f, 0x03, 0x0b, 0x56, 0x8a,
	0xd5, 0x13, 0xbb, 0xbc, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xfa, 0x3c, 0x01, 0x54, 0x08,
	0x00, 0x00,
}
